spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://localhost:3306/xc166_content?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: cxzly8023
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml


